services:
  - type: web
    name: live-score-scraper-client
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python -m playwright install chromium
    startCommand: gunicorn web_portal.web_app:app --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 180
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
